In [2]:
# ! pip install pandas

Collecting pandas
  Downloading pandas-2.3.3-cp310-cp310-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.22.4 in c:\it\workspace_python\.venv\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\it\workspace_python\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: tzdata>=2022.7 in c:\it\workspace_python\.venv\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\it\workspace_python\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.3.3-cp310-cp310-win_amd64.whl (11.3 MB)
   ---------------------------------------- 0.0/11.3 MB ? eta -:--:--
   -------- ------------------------------- 2.4/11.3 MB 11.2 MB/s eta 0:00:01
   ---------------- ----------------------- 4.7/11.3 MB 11.9 MB/s eta 0:00:01
   ---------------------- ----------------- 6.3/11.3 MB 10.2 MB/s eta 0:00:01
   ------------------------------ --------- 8.7/11.3 MB 10.5 MB/s eta 0:00:01
   ---------------------------------------  11.3/11.3 MB 10.8 MB/s eta 0:00:01
   ---------------------------------------- 11.3/11.3 MB 10.6 MB/s eta 0:00:00
Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
Installing collected packages: pytz, pandas

   ---------------------------------------- 0/2 [pytz]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   ---------------------------------------- 2/2 [pandas]

Successfully installed pandas-2.3.3 pytz-2025.2

[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import pandas as pd

In [7]:
raw_data = pd.read_csv('raw_data.csv')

In [9]:
raw_data.head()

,game_id,action_id,period_id,time_seconds,team_id,player_id,result_name,start_x,start_y,end_x,end_y,dx,dy,type_name,player_name_ko,team_name_ko,position_name,main_position
0,126288,0,1,1.033,2353,356625.0,Successful,52.670205,34.919632,68.628945,34.347412,15.958740,-0.572220,Pass,이영준,김천 상무 프로축구단,CF,CF
1,126288,1,1,2.433,2353,356612.0,NaN,68.628945,34.347412,68.628945,34.347412,0.000000,0.000000,Pass Received,원두재,김천 상무 프로축구단,CDM,CM
2,126288,2,1,3.033,2353,356612.0,Successful,68.228055,33.853256,65.468865,26.640292,-2.759190,-7.212964,Pass,원두재,김천 상무 프로축구단,CDM,CM
3,126288,3,1,4.333,2353,356618.0,NaN,65.468865,26.640292,65.468865,26.640292,0.000000,0.000000,Pass Received,김진규,김천 상무 프로축구단,CM,CM
4,126288,4,1,4.900,2353,356618.0,Successful,64.838025,26.766636,63.300510,43.018024,-1.537515,16.251388,Pass,김진규,김천 상무 프로축구단,CM,CM

In [16]:
pass_received = raw_data.loc[raw_data['type_name']=='Pass Received',
    ["game_id", "period_id", "team_id", "player_id", "result_name", "type_name", "player_name_ko", "team_name_ko", "position_name", "main_position"]]
pass_received.head()

,game_id,period_id,team_id,player_id,result_name,type_name,player_name_ko,team_name_ko,position_name,main_position
1,126288,1,2353,356612.0,NaN,Pass Received,원두재,김천 상무 프로축구단,CDM,CM
3,126288,1,2353,356618.0,NaN,Pass Received,김진규,김천 상무 프로축구단,CM,CM
5,126288,1,2353,356624.0,NaN,Pass Received,강현묵,김천 상무 프로축구단,CM,CM
8,126288,1,2353,356612.0,NaN,Pass Received,원두재,김천 상무 프로축구단,CDM,CM
11,126288,1,2353,356619.0,NaN,Pass Received,김재우,김천 상무 프로축구단,CB,CB

In [18]:
raw_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 579306 entries, 0 to 579305
Data columns (total 18 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   game_id         579306 non-null  int64
 1   action_id       579306 non-null  int64
 2   period_id       579306 non-null  int64
 3   time_seconds    579306 non-null  float64
 4   team_id         579306 non-null  int64
 5   player_id       579305 non-null  float64
 6   result_name     229702 non-null  object
 7   start_x         579306 non-null  float64
 8   start_y         579306 non-null  float64
 9   end_x           579306 non-null  float64
 10  end_y           579306 non-null  float64
 11  dx              579306 non-null  float64
 12  dy              579306 non-null  float64
 13  type_name       579306 non-null  object
 14  player_name_ko  579305 non-null  object
 15  team_name_ko    579306 non-null  object
 16  position_name   509186 non-null  object
 17  main_position   577602 non-null  object
dtypes: float64(8), int64(4), object(6)
memory usage: 79.6+ MB